name: diting2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.9
  - snakemake>=9.0
  - pandas
  - matplotlib-base
  - seaborn
  - megahit
  - spades
  - prodigal
  - bwa
  - bbmap
  - hmmer>=3.3
  - opencv
  - pillow
  - kofamscan
  - pip
  - pip:
    - .
