[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "diting"
version = "2.0.2"
description = "A Pipeline to Infer and Compare Biogeochemical Pathways From Metagenomic and Metatranscriptomic Data"
readme = "README.md"
authors = [
    { name = "Heyu Lin", email = "heyu.lin@qut.edu.au" },
    { name = "Xue Chunxu", email = "xuechunxu@outlook.com" }
    
]
requires-python = ">=3.9"
dependencies = [
    "snakemake>=9.0",
    "pandas",
    "matplotlib",
    "seaborn",
    "Pillow",
    "opencv-python"
]

[project.scripts]
diting = "diting.cli:main"
diting-download-db = "diting.download_db:main"

[tool.hatch.build.targets.sdist]
include = [
    "diting",
]

[tool.hatch.build.targets.wheel]
include = [
    "diting",
]
